version: "3.8"

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./challenges:/app/challenges
      - ./final_challenges:/app/final_challenges
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_KEY=${TAVILY_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - USE_MONGODB=${USE_MONGODB}
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
