version: "3.8"

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./challenges:/app/challenges
      - ./final_challenges:/app/final_challenges
      - ./secrets/.env:/app/.env:ro
    env_file:
      - ./secrets/.env
    restart: unless-stopped
