version: "3.8"

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./challenges:/app/challenges
      - ./final_challenges:/app/final_challenges
      - ./secrets/.env:/app/.env:ro
    env_file:
      - ./secrets/.env
    networks:
      - app_network
    restart: unless-stopped
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - USE_MONGODB=${USE_MONGODB}
      # Add other environment variables as needed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge